// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: captcha.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取验证码请求参数
type MakeCaptchaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码高度
	Height int32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// 验证码宽度
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// 验证码长度
	Length        int32 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeCaptchaRequest) Reset() {
	*x = MakeCaptchaRequest{}
	mi := &file_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCaptchaRequest) ProtoMessage() {}

func (x *MakeCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCaptchaRequest.ProtoReflect.Descriptor instead.
func (*MakeCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{0}
}

func (x *MakeCaptchaRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MakeCaptchaRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MakeCaptchaRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// 获取验证码返回数据
type MakeCaptchaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 验证码base64编码
	B64S          string `protobuf:"bytes,2,opt,name=b64s,proto3" json:"b64s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeCaptchaResponse) Reset() {
	*x = MakeCaptchaResponse{}
	mi := &file_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCaptchaResponse) ProtoMessage() {}

func (x *MakeCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCaptchaResponse.ProtoReflect.Descriptor instead.
func (*MakeCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{1}
}

func (x *MakeCaptchaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MakeCaptchaResponse) GetB64S() string {
	if x != nil {
		return x.B64S
	}
	return ""
}

// 校验验证码请求参数
type VerifyCaptchaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 输入的验证码
	VerifyValue   string `protobuf:"bytes,2,opt,name=verifyValue,proto3" json:"verifyValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaRequest) Reset() {
	*x = VerifyCaptchaRequest{}
	mi := &file_captcha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaRequest) ProtoMessage() {}

func (x *VerifyCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaRequest.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCaptchaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyCaptchaRequest) GetVerifyValue() string {
	if x != nil {
		return x.VerifyValue
	}
	return ""
}

// 校验验证码返回数据
type VerifyCaptchaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 校验的结果
	VerifyResult  bool `protobuf:"varint,1,opt,name=verifyResult,proto3" json:"verifyResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaResponse) Reset() {
	*x = VerifyCaptchaResponse{}
	mi := &file_captcha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaResponse) ProtoMessage() {}

func (x *VerifyCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaResponse.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_captcha_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCaptchaResponse) GetVerifyResult() bool {
	if x != nil {
		return x.VerifyResult
	}
	return false
}

var File_captcha_proto protoreflect.FileDescriptor

const file_captcha_proto_rawDesc = "" +
	"\n" +
	"\rcaptcha.proto\"Z\n" +
	"\x12MakeCaptchaRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\"9\n" +
	"\x13MakeCaptchaResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04b64s\x18\x02 \x01(\tR\x04b64s\"H\n" +
	"\x14VerifyCaptchaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vverifyValue\x18\x02 \x01(\tR\vverifyValue\";\n" +
	"\x15VerifyCaptchaResponse\x12\"\n" +
	"\fverifyResult\x18\x01 \x01(\bR\fverifyResult2\x8b\x01\n" +
	"\aCaptcha\x12>\n" +
	"\x0fGenerateCaptcha\x12\x13.MakeCaptchaRequest\x1a\x14.MakeCaptchaResponse\"\x00\x12@\n" +
	"\rVerifyCaptcha\x12\x15.VerifyCaptchaRequest\x1a\x16.VerifyCaptchaResponse\"\x00B\tZ\a.;protob\x06proto3"

var (
	file_captcha_proto_rawDescOnce sync.Once
	file_captcha_proto_rawDescData []byte
)

func file_captcha_proto_rawDescGZIP() []byte {
	file_captcha_proto_rawDescOnce.Do(func() {
		file_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_captcha_proto_rawDesc), len(file_captcha_proto_rawDesc)))
	})
	return file_captcha_proto_rawDescData
}

var file_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_captcha_proto_goTypes = []any{
	(*MakeCaptchaRequest)(nil),    // 0: MakeCaptchaRequest
	(*MakeCaptchaResponse)(nil),   // 1: MakeCaptchaResponse
	(*VerifyCaptchaRequest)(nil),  // 2: VerifyCaptchaRequest
	(*VerifyCaptchaResponse)(nil), // 3: VerifyCaptchaResponse
}
var file_captcha_proto_depIdxs = []int32{
	0, // 0: Captcha.GenerateCaptcha:input_type -> MakeCaptchaRequest
	2, // 1: Captcha.VerifyCaptcha:input_type -> VerifyCaptchaRequest
	1, // 2: Captcha.GenerateCaptcha:output_type -> MakeCaptchaResponse
	3, // 3: Captcha.VerifyCaptcha:output_type -> VerifyCaptchaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_captcha_proto_init() }
func file_captcha_proto_init() {
	if File_captcha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_captcha_proto_rawDesc), len(file_captcha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_captcha_proto_goTypes,
		DependencyIndexes: file_captcha_proto_depIdxs,
		MessageInfos:      file_captcha_proto_msgTypes,
	}.Build()
	File_captcha_proto = out.File
	file_captcha_proto_goTypes = nil
	file_captcha_proto_depIdxs = nil
}
