name: 'user-web'
port: 8022
user-srv:
  host: '127.0.0.1'
  port: 5001

jwt:
  key: aaaaabbbcddbd

sms:
  accessKeyId: "xxxx"
  accessKeySecret: "xxxx"
  protocol: "https"
  regionId: "xxx"
  domain: "xxx"
  signName: "xxx"
  templateCode: "xxxx"
  apiName: "xxx"


