name: 'user-web'
port: 8022
user-srv:
  host: '127.0.0.1'
  port: 5001
  name: 'user-srv'

system:
  use-redis: true

jwt:
  key: aaaaabbbcddbd
### 短信配置

### redis配置
redis:
  host: "127.0.0.1"
  port: 6379

## consul
consul:
  host: '127.0.0.1'
  port: 8500

