# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: role.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from common.proto.pb import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrole.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x63ommon.proto\"A\n\x11\x43reateRoleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06remark\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\"H\n\x0cRoleResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\"M\n\x11UpdateRoleRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\"o\n\x15RoleFilterPageRequest\x12(\n\x0bpageRequest\x18\x01 \x01(\x0b\x32\x13.common.PageRequest\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\">\n\x10RoleListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1b\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\r.RoleResponse2\xaf\x01\n\x04Role\x12/\n\nCreateRole\x12\x12.CreateRoleRequest\x1a\r.RoleResponse\x12\x38\n\nUpdateRole\x12\x12.UpdateRoleRequest\x1a\x16.google.protobuf.Empty\x12<\n\x0fGetRolePageList\x12\x16.RoleFilterPageRequest\x1a\x11.RoleListResponseB\tZ\x07.;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007.;proto'
  _globals['_CREATEROLEREQUEST']._serialized_start=57
  _globals['_CREATEROLEREQUEST']._serialized_end=122
  _globals['_ROLERESPONSE']._serialized_start=124
  _globals['_ROLERESPONSE']._serialized_end=196
  _globals['_UPDATEROLEREQUEST']._serialized_start=198
  _globals['_UPDATEROLEREQUEST']._serialized_end=275
  _globals['_ROLEFILTERPAGEREQUEST']._serialized_start=277
  _globals['_ROLEFILTERPAGEREQUEST']._serialized_end=388
  _globals['_ROLELISTRESPONSE']._serialized_start=390
  _globals['_ROLELISTRESPONSE']._serialized_end=452
  _globals['_ROLE']._serialized_start=455
  _globals['_ROLE']._serialized_end=630
# @@protoc_insertion_point(module_scope)
