"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateDictTypeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYSTEMFLAG_FIELD_NUMBER: builtins.int
    DICTCODE_FIELD_NUMBER: builtins.int
    DICTNAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    systemFlag: builtins.bool
    dictCode: builtins.str
    dictName: builtins.str
    remark: builtins.str
    status: builtins.bool
    def __init__(
        self,
        *,
        systemFlag: builtins.bool = ...,
        dictCode: builtins.str = ...,
        dictName: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dictCode", b"dictCode", "dictName", b"dictName", "remark", b"remark", "status", b"status", "systemFlag", b"systemFlag"]) -> None: ...

global___CreateDictTypeRequest = CreateDictTypeRequest

@typing.final
class DictTypeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SYSTEMFLAG_FIELD_NUMBER: builtins.int
    DICTCODE_FIELD_NUMBER: builtins.int
    DICTNAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    TIMESTAMPRESPONSE_FIELD_NUMBER: builtins.int
    id: builtins.int
    systemFlag: builtins.bool
    dictCode: builtins.str
    dictName: builtins.str
    remark: builtins.str
    status: builtins.bool
    @property
    def timestampResponse(self) -> common_pb2.TimestampResponse: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        systemFlag: builtins.bool = ...,
        dictCode: builtins.str = ...,
        dictName: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
        timestampResponse: common_pb2.TimestampResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestampResponse", b"timestampResponse"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["dictCode", b"dictCode", "dictName", b"dictName", "id", b"id", "remark", b"remark", "status", b"status", "systemFlag", b"systemFlag", "timestampResponse", b"timestampResponse"]) -> None: ...

global___DictTypeResponse = DictTypeResponse

@typing.final
class UpdateDictTypeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    remark: builtins.str
    status: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name", "remark", b"remark", "status", b"status"]) -> None: ...

global___UpdateDictTypeRequest = UpdateDictTypeRequest

@typing.final
class DictTypeFilterPageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGEREQUEST_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    remark: builtins.str
    status: builtins.bool
    @property
    def pageRequest(self) -> common_pb2.PageRequest:
        """分页参数"""

    def __init__(
        self,
        *,
        pageRequest: common_pb2.PageRequest | None = ...,
        name: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pageRequest", b"pageRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "pageRequest", b"pageRequest", "remark", b"remark", "status", b"status"]) -> None: ...

global___DictTypeFilterPageRequest = DictTypeFilterPageRequest

@typing.final
class DictTypeListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_FIELD_NUMBER: builtins.int
    LIST_FIELD_NUMBER: builtins.int
    @property
    def page(self) -> common_pb2.PageResponse: ...
    @property
    def list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DictTypeResponse]: ...
    def __init__(
        self,
        *,
        page: common_pb2.PageResponse | None = ...,
        list: collections.abc.Iterable[global___DictTypeResponse] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["page", b"page"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["list", b"list", "page", b"page"]) -> None: ...

global___DictTypeListResponse = DictTypeListResponse

@typing.final
class CreateDictItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    remark: builtins.str
    status: builtins.bool
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "remark", b"remark", "status", b"status"]) -> None: ...

global___CreateDictItemRequest = CreateDictItemRequest

@typing.final
class DictItemResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    remark: builtins.str
    status: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name", "remark", b"remark", "status", b"status"]) -> None: ...

global___DictItemResponse = DictItemResponse

@typing.final
class UpdateDictItemRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    remark: builtins.str
    status: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name", "remark", b"remark", "status", b"status"]) -> None: ...

global___UpdateDictItemRequest = UpdateDictItemRequest

@typing.final
class DictItemFilterPageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGEREQUEST_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    remark: builtins.str
    status: builtins.bool
    @property
    def pageRequest(self) -> common_pb2.PageRequest:
        """分页参数"""

    def __init__(
        self,
        *,
        pageRequest: common_pb2.PageRequest | None = ...,
        name: builtins.str = ...,
        remark: builtins.str = ...,
        status: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pageRequest", b"pageRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "pageRequest", b"pageRequest", "remark", b"remark", "status", b"status"]) -> None: ...

global___DictItemFilterPageRequest = DictItemFilterPageRequest

@typing.final
class DictItemPageListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def page(self) -> common_pb2.PageResponse: ...
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DictItemResponse]: ...
    def __init__(
        self,
        *,
        page: common_pb2.PageResponse | None = ...,
        data: collections.abc.Iterable[global___DictItemResponse] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["page", b"page"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "page", b"page"]) -> None: ...

global___DictItemPageListResponse = DictItemPageListResponse
