"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GoodsInvInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GOODSID_FIELD_NUMBER: builtins.int
    NUM_FIELD_NUMBER: builtins.int
    goodsId: builtins.int
    num: builtins.int
    def __init__(
        self,
        *,
        goodsId: builtins.int = ...,
        num: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["goodsId", b"goodsId", "num", b"num"]) -> None: ...

global___GoodsInvInfo = GoodsInvInfo

@typing.final
class SellInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GOODSINFO_FIELD_NUMBER: builtins.int
    @property
    def goodsInfo(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GoodsInvInfo]: ...
    def __init__(
        self,
        *,
        goodsInfo: collections.abc.Iterable[global___GoodsInvInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["goodsInfo", b"goodsInfo"]) -> None: ...

global___SellInfo = SellInfo
