"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserFavFilterPageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    GOODSID_FIELD_NUMBER: builtins.int
    userId: builtins.int
    goodsId: builtins.int
    def __init__(
        self,
        *,
        userId: builtins.int = ...,
        goodsId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["goodsId", b"goodsId", "userId", b"userId"]) -> None: ...

global___UserFavFilterPageRequest = UserFavFilterPageRequest

@typing.final
class CreateUserFavRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    GOODSID_FIELD_NUMBER: builtins.int
    userId: builtins.int
    goodsId: builtins.int
    def __init__(
        self,
        *,
        userId: builtins.int = ...,
        goodsId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["goodsId", b"goodsId", "userId", b"userId"]) -> None: ...

global___CreateUserFavRequest = CreateUserFavRequest

@typing.final
class UserFavResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    GOODSID_FIELD_NUMBER: builtins.int
    userId: builtins.int
    goodsId: builtins.int
    def __init__(
        self,
        *,
        userId: builtins.int = ...,
        goodsId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["goodsId", b"goodsId", "userId", b"userId"]) -> None: ...

global___UserFavResponse = UserFavResponse

@typing.final
class UserFavDetailResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    GOODSID_FIELD_NUMBER: builtins.int
    userId: builtins.int
    goodsId: builtins.int
    def __init__(
        self,
        *,
        userId: builtins.int = ...,
        goodsId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["goodsId", b"goodsId", "userId", b"userId"]) -> None: ...

global___UserFavDetailResponse = UserFavDetailResponse

@typing.final
class UserFavListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    total: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserFavResponse]: ...
    def __init__(
        self,
        *,
        total: builtins.int = ...,
        data: collections.abc.Iterable[global___UserFavResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "total", b"total"]) -> None: ...

global___UserFavListResponse = UserFavListResponse
