// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: dict.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemFlag    bool                   `protobuf:"varint,1,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	DictCode      string                 `protobuf:"bytes,2,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	DictName      string                 `protobuf:"bytes,3,opt,name=dictName,proto3" json:"dictName,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictTypeRequest) Reset() {
	*x = CreateDictTypeRequest{}
	mi := &file_dict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictTypeRequest) ProtoMessage() {}

func (x *CreateDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDictTypeRequest) GetSystemFlag() bool {
	if x != nil {
		return x.SystemFlag
	}
	return false
}

func (x *CreateDictTypeRequest) GetDictCode() string {
	if x != nil {
		return x.DictCode
	}
	return ""
}

func (x *CreateDictTypeRequest) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *CreateDictTypeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateDictTypeRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DictTypeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemFlag        bool                   `protobuf:"varint,2,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	DictCode          string                 `protobuf:"bytes,3,opt,name=dictCode,proto3" json:"dictCode,omitempty"`
	DictName          string                 `protobuf:"bytes,4,opt,name=dictName,proto3" json:"dictName,omitempty"`
	Remark            string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Status            bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	TimestampResponse *TimestampResponse     `protobuf:"bytes,7,opt,name=timestampResponse,proto3" json:"timestampResponse,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DictTypeResponse) Reset() {
	*x = DictTypeResponse{}
	mi := &file_dict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTypeResponse) ProtoMessage() {}

func (x *DictTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTypeResponse.ProtoReflect.Descriptor instead.
func (*DictTypeResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{1}
}

func (x *DictTypeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictTypeResponse) GetSystemFlag() bool {
	if x != nil {
		return x.SystemFlag
	}
	return false
}

func (x *DictTypeResponse) GetDictCode() string {
	if x != nil {
		return x.DictCode
	}
	return ""
}

func (x *DictTypeResponse) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *DictTypeResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictTypeResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DictTypeResponse) GetTimestampResponse() *TimestampResponse {
	if x != nil {
		return x.TimestampResponse
	}
	return nil
}

type UpdateDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictTypeRequest) Reset() {
	*x = UpdateDictTypeRequest{}
	mi := &file_dict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictTypeRequest) ProtoMessage() {}

func (x *UpdateDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDictTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DictTypeFilterPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageRequest   *PageRequest           `protobuf:"bytes,1,opt,name=pageRequest,proto3" json:"pageRequest,omitempty"` // 分页参数
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictTypeFilterPageRequest) Reset() {
	*x = DictTypeFilterPageRequest{}
	mi := &file_dict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTypeFilterPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTypeFilterPageRequest) ProtoMessage() {}

func (x *DictTypeFilterPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTypeFilterPageRequest.ProtoReflect.Descriptor instead.
func (*DictTypeFilterPageRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{3}
}

func (x *DictTypeFilterPageRequest) GetPageRequest() *PageRequest {
	if x != nil {
		return x.PageRequest
	}
	return nil
}

func (x *DictTypeFilterPageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DictTypeFilterPageRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictTypeFilterPageRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DictTypeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	List          []*DictTypeResponse    `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictTypeListResponse) Reset() {
	*x = DictTypeListResponse{}
	mi := &file_dict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTypeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTypeListResponse) ProtoMessage() {}

func (x *DictTypeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTypeListResponse.ProtoReflect.Descriptor instead.
func (*DictTypeListResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{4}
}

func (x *DictTypeListResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *DictTypeListResponse) GetList() []*DictTypeResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateDictItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictItemRequest) Reset() {
	*x = CreateDictItemRequest{}
	mi := &file_dict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictItemRequest) ProtoMessage() {}

func (x *CreateDictItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictItemRequest.ProtoReflect.Descriptor instead.
func (*CreateDictItemRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDictItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDictItemRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateDictItemRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DictItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictItemResponse) Reset() {
	*x = DictItemResponse{}
	mi := &file_dict_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictItemResponse) ProtoMessage() {}

func (x *DictItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictItemResponse.ProtoReflect.Descriptor instead.
func (*DictItemResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{6}
}

func (x *DictItemResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DictItemResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictItemResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateDictItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictItemRequest) Reset() {
	*x = UpdateDictItemRequest{}
	mi := &file_dict_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictItemRequest) ProtoMessage() {}

func (x *UpdateDictItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictItemRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDictItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDictItemRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateDictItemRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DictItemFilterPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageRequest   *PageRequest           `protobuf:"bytes,1,opt,name=pageRequest,proto3" json:"pageRequest,omitempty"` // 分页参数
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictItemFilterPageRequest) Reset() {
	*x = DictItemFilterPageRequest{}
	mi := &file_dict_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictItemFilterPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictItemFilterPageRequest) ProtoMessage() {}

func (x *DictItemFilterPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictItemFilterPageRequest.ProtoReflect.Descriptor instead.
func (*DictItemFilterPageRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{8}
}

func (x *DictItemFilterPageRequest) GetPageRequest() *PageRequest {
	if x != nil {
		return x.PageRequest
	}
	return nil
}

func (x *DictItemFilterPageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DictItemFilterPageRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DictItemFilterPageRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DictItemPageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Data          []*DictItemResponse    `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictItemPageListResponse) Reset() {
	*x = DictItemPageListResponse{}
	mi := &file_dict_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictItemPageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictItemPageListResponse) ProtoMessage() {}

func (x *DictItemPageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictItemPageListResponse.ProtoReflect.Descriptor instead.
func (*DictItemPageListResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{9}
}

func (x *DictItemPageListResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *DictItemPageListResponse) GetData() []*DictItemResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_dict_proto protoreflect.FileDescriptor

const file_dict_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dict.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"\x9f\x01\n" +
	"\x15CreateDictTypeRequest\x12\x1e\n" +
	"\n" +
	"systemFlag\x18\x01 \x01(\bR\n" +
	"systemFlag\x12\x1a\n" +
	"\bdictCode\x18\x02 \x01(\tR\bdictCode\x12\x1a\n" +
	"\bdictName\x18\x03 \x01(\tR\bdictName\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\"\xf3\x01\n" +
	"\x10DictTypeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"systemFlag\x18\x02 \x01(\bR\n" +
	"systemFlag\x12\x1a\n" +
	"\bdictCode\x18\x03 \x01(\tR\bdictCode\x12\x1a\n" +
	"\bdictName\x18\x04 \x01(\tR\bdictName\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12G\n" +
	"\x11timestampResponse\x18\a \x01(\v2\x19.common.TimestampResponseR\x11timestampResponse\"k\n" +
	"\x15UpdateDictTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"\x96\x01\n" +
	"\x19DictTypeFilterPageRequest\x125\n" +
	"\vpageRequest\x18\x01 \x01(\v2\x13.common.PageRequestR\vpageRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"g\n" +
	"\x14DictTypeListResponse\x12(\n" +
	"\x04page\x18\x01 \x01(\v2\x14.common.PageResponseR\x04page\x12%\n" +
	"\x04list\x18\x02 \x03(\v2\x11.DictTypeResponseR\x04list\"[\n" +
	"\x15CreateDictItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"f\n" +
	"\x10DictItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"k\n" +
	"\x15UpdateDictItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"\x96\x01\n" +
	"\x19DictItemFilterPageRequest\x125\n" +
	"\vpageRequest\x18\x01 \x01(\v2\x13.common.PageRequestR\vpageRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"k\n" +
	"\x18DictItemPageListResponse\x12(\n" +
	"\x04page\x18\x01 \x01(\v2\x14.common.PageResponseR\x04page\x12%\n" +
	"\x04data\x18\x02 \x03(\v2\x11.DictItemResponseR\x04data2\xa2\x04\n" +
	"\x04Dict\x12;\n" +
	"\x0eCreateDictType\x12\x16.CreateDictTypeRequest\x1a\x11.DictTypeResponse\x12@\n" +
	"\x0eUpdateDictType\x12\x16.UpdateDictTypeRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x13GetDictTypePageList\x12\x1a.DictTypeFilterPageRequest\x1a\x15.DictTypeListResponse\x12A\n" +
	"\x13DeleteDictTypeByIds\x12\x12.common.IdsRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x0eCreateDictItem\x12\x16.CreateDictItemRequest\x1a\x11.DictItemResponse\x12@\n" +
	"\x0eUpdateDictItem\x12\x16.UpdateDictItemRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x13GetDictItemPageList\x12\x1a.DictItemFilterPageRequest\x1a\x19.DictItemPageListResponse\x12A\n" +
	"\x13DeleteDictItemByIds\x12\x12.common.IdsRequest\x1a\x16.google.protobuf.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_dict_proto_rawDescOnce sync.Once
	file_dict_proto_rawDescData []byte
)

func file_dict_proto_rawDescGZIP() []byte {
	file_dict_proto_rawDescOnce.Do(func() {
		file_dict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dict_proto_rawDesc), len(file_dict_proto_rawDesc)))
	})
	return file_dict_proto_rawDescData
}

var file_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dict_proto_goTypes = []any{
	(*CreateDictTypeRequest)(nil),     // 0: CreateDictTypeRequest
	(*DictTypeResponse)(nil),          // 1: DictTypeResponse
	(*UpdateDictTypeRequest)(nil),     // 2: UpdateDictTypeRequest
	(*DictTypeFilterPageRequest)(nil), // 3: DictTypeFilterPageRequest
	(*DictTypeListResponse)(nil),      // 4: DictTypeListResponse
	(*CreateDictItemRequest)(nil),     // 5: CreateDictItemRequest
	(*DictItemResponse)(nil),          // 6: DictItemResponse
	(*UpdateDictItemRequest)(nil),     // 7: UpdateDictItemRequest
	(*DictItemFilterPageRequest)(nil), // 8: DictItemFilterPageRequest
	(*DictItemPageListResponse)(nil),  // 9: DictItemPageListResponse
	(*TimestampResponse)(nil),         // 10: common.TimestampResponse
	(*PageRequest)(nil),               // 11: common.PageRequest
	(*PageResponse)(nil),              // 12: common.PageResponse
	(*IdsRequest)(nil),                // 13: common.IdsRequest
	(*emptypb.Empty)(nil),             // 14: google.protobuf.Empty
}
var file_dict_proto_depIdxs = []int32{
	10, // 0: DictTypeResponse.timestampResponse:type_name -> common.TimestampResponse
	11, // 1: DictTypeFilterPageRequest.pageRequest:type_name -> common.PageRequest
	12, // 2: DictTypeListResponse.page:type_name -> common.PageResponse
	1,  // 3: DictTypeListResponse.list:type_name -> DictTypeResponse
	11, // 4: DictItemFilterPageRequest.pageRequest:type_name -> common.PageRequest
	12, // 5: DictItemPageListResponse.page:type_name -> common.PageResponse
	6,  // 6: DictItemPageListResponse.data:type_name -> DictItemResponse
	0,  // 7: Dict.CreateDictType:input_type -> CreateDictTypeRequest
	2,  // 8: Dict.UpdateDictType:input_type -> UpdateDictTypeRequest
	3,  // 9: Dict.GetDictTypePageList:input_type -> DictTypeFilterPageRequest
	13, // 10: Dict.DeleteDictTypeByIds:input_type -> common.IdsRequest
	5,  // 11: Dict.CreateDictItem:input_type -> CreateDictItemRequest
	7,  // 12: Dict.UpdateDictItem:input_type -> UpdateDictItemRequest
	8,  // 13: Dict.GetDictItemPageList:input_type -> DictItemFilterPageRequest
	13, // 14: Dict.DeleteDictItemByIds:input_type -> common.IdsRequest
	1,  // 15: Dict.CreateDictType:output_type -> DictTypeResponse
	14, // 16: Dict.UpdateDictType:output_type -> google.protobuf.Empty
	4,  // 17: Dict.GetDictTypePageList:output_type -> DictTypeListResponse
	14, // 18: Dict.DeleteDictTypeByIds:output_type -> google.protobuf.Empty
	6,  // 19: Dict.CreateDictItem:output_type -> DictItemResponse
	14, // 20: Dict.UpdateDictItem:output_type -> google.protobuf.Empty
	9,  // 21: Dict.GetDictItemPageList:output_type -> DictItemPageListResponse
	14, // 22: Dict.DeleteDictItemByIds:output_type -> google.protobuf.Empty
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dict_proto_init() }
func file_dict_proto_init() {
	if File_dict_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dict_proto_rawDesc), len(file_dict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dict_proto_goTypes,
		DependencyIndexes: file_dict_proto_depIdxs,
		MessageInfos:      file_dict_proto_msgTypes,
	}.Build()
	File_dict_proto = out.File
	file_dict_proto_goTypes = nil
	file_dict_proto_depIdxs = nil
}
