// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: goods.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsFilterRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PriceMin    int32                  `protobuf:"varint,1,opt,name=priceMin,proto3" json:"priceMin,omitempty"`
	PriceMax    int32                  `protobuf:"varint,2,opt,name=priceMax,proto3" json:"priceMax,omitempty"`
	IsHot       bool                   `protobuf:"varint,3,opt,name=isHot,proto3" json:"isHot,omitempty"`
	IsNew       bool                   `protobuf:"varint,4,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsTab       bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	TopCategory int32                  `protobuf:"varint,6,opt,name=topCategory,proto3" json:"topCategory,omitempty"`
	// 页码
	Page uint32 `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	// 每页大小
	Size          uint32 `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	KeyWords      string `protobuf:"bytes,9,opt,name=keyWords,proto3" json:"keyWords,omitempty"`
	Brand         int32  `protobuf:"varint,10,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsFilterRequest) Reset() {
	*x = GoodsFilterRequest{}
	mi := &file_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsFilterRequest) ProtoMessage() {}

func (x *GoodsFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsFilterRequest.ProtoReflect.Descriptor instead.
func (*GoodsFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsFilterRequest) GetPriceMin() int32 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *GoodsFilterRequest) GetPriceMax() int32 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *GoodsFilterRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodsFilterRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodsFilterRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *GoodsFilterRequest) GetTopCategory() int32 {
	if x != nil {
		return x.TopCategory
	}
	return 0
}

func (x *GoodsFilterRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsFilterRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GoodsFilterRequest) GetKeyWords() string {
	if x != nil {
		return x.KeyWords
	}
	return ""
}

func (x *GoodsFilterRequest) GetBrand() int32 {
	if x != nil {
		return x.Brand
	}
	return 0
}

type GoodsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*GoodsInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListResponse) Reset() {
	*x = GoodsListResponse{}
	mi := &file_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListResponse) ProtoMessage() {}

func (x *GoodsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListResponse.ProtoReflect.Descriptor instead.
func (*GoodsListResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GoodsListResponse) GetData() []*GoodsInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchGoodsIdInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int32                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGoodsIdInfo) Reset() {
	*x = BatchGoodsIdInfo{}
	mi := &file_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGoodsIdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGoodsIdInfo) ProtoMessage() {}

func (x *BatchGoodsIdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGoodsIdInfo.ProtoReflect.Descriptor instead.
func (*BatchGoodsIdInfo) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGoodsIdInfo) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

type CreateGoodsInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GoodsSn         string                 `protobuf:"bytes,3,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`
	Stocks          int32                  `protobuf:"varint,7,opt,name=stocks,proto3" json:"stocks,omitempty"` // 库存
	MarketPrice     float32                `protobuf:"fixed32,8,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	ShopPrice       float32                `protobuf:"fixed32,9,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`
	GoodsBrief      string                 `protobuf:"bytes,10,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`
	GoodsDesc       string                 `protobuf:"bytes,11,opt,name=goodsDesc,proto3" json:"goodsDesc,omitempty"`
	ShipFree        bool                   `protobuf:"varint,12,opt,name=shipFree,proto3" json:"shipFree,omitempty"`
	Images          []string               `protobuf:"bytes,13,rep,name=images,proto3" json:"images,omitempty"`
	DescImages      []string               `protobuf:"bytes,14,rep,name=descImages,proto3" json:"descImages,omitempty"`
	GoodsFrontImage string                 `protobuf:"bytes,15,opt,name=goodsFrontImage,proto3" json:"goodsFrontImage,omitempty"`
	IsNew           bool                   `protobuf:"varint,16,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsHot           bool                   `protobuf:"varint,17,opt,name=isHot,proto3" json:"isHot,omitempty"`
	OnSale          bool                   `protobuf:"varint,18,opt,name=onSale,proto3" json:"onSale,omitempty"`
	CategoryId      int32                  `protobuf:"varint,19,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	BrandId         int32                  `protobuf:"varint,20,opt,name=brandId,proto3" json:"brandId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGoodsInfo) Reset() {
	*x = CreateGoodsInfo{}
	mi := &file_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsInfo) ProtoMessage() {}

func (x *CreateGoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsInfo.ProtoReflect.Descriptor instead.
func (*CreateGoodsInfo) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGoodsInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateGoodsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGoodsInfo) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *CreateGoodsInfo) GetStocks() int32 {
	if x != nil {
		return x.Stocks
	}
	return 0
}

func (x *CreateGoodsInfo) GetMarketPrice() float32 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *CreateGoodsInfo) GetShopPrice() float32 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *CreateGoodsInfo) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *CreateGoodsInfo) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *CreateGoodsInfo) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *CreateGoodsInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateGoodsInfo) GetDescImages() []string {
	if x != nil {
		return x.DescImages
	}
	return nil
}

func (x *CreateGoodsInfo) GetGoodsFrontImage() string {
	if x != nil {
		return x.GoodsFrontImage
	}
	return ""
}

func (x *CreateGoodsInfo) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CreateGoodsInfo) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *CreateGoodsInfo) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *CreateGoodsInfo) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateGoodsInfo) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

type CategoryBriefInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBriefInfoResponse) Reset() {
	*x = CategoryBriefInfoResponse{}
	mi := &file_goods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBriefInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBriefInfoResponse) ProtoMessage() {}

func (x *CategoryBriefInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBriefInfoResponse.ProtoReflect.Descriptor instead.
func (*CategoryBriefInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryBriefInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBriefInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GoodsInfoResponse struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Id              int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId      int32                      `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Name            string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GoodsSn         string                     `protobuf:"bytes,4,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`
	ClickNum        int32                      `protobuf:"varint,5,opt,name=clickNum,proto3" json:"clickNum,omitempty"`
	SoldNum         int32                      `protobuf:"varint,6,opt,name=soldNum,proto3" json:"soldNum,omitempty"`
	FavNum          int32                      `protobuf:"varint,7,opt,name=favNum,proto3" json:"favNum,omitempty"`
	MarketPrice     float32                    `protobuf:"fixed32,9,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	ShopPrice       float32                    `protobuf:"fixed32,10,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`
	GoodsBrief      string                     `protobuf:"bytes,11,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`
	GoodsDesc       string                     `protobuf:"bytes,12,opt,name=goodsDesc,proto3" json:"goodsDesc,omitempty"`
	ShipFree        bool                       `protobuf:"varint,13,opt,name=shipFree,proto3" json:"shipFree,omitempty"`
	Images          []string                   `protobuf:"bytes,14,rep,name=images,proto3" json:"images,omitempty"`
	DescImages      []string                   `protobuf:"bytes,15,rep,name=descImages,proto3" json:"descImages,omitempty"`
	GoodsFrontImage string                     `protobuf:"bytes,16,opt,name=goodsFrontImage,proto3" json:"goodsFrontImage,omitempty"`
	IsNew           bool                       `protobuf:"varint,17,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsHot           bool                       `protobuf:"varint,18,opt,name=isHot,proto3" json:"isHot,omitempty"`
	OnSale          bool                       `protobuf:"varint,19,opt,name=onSale,proto3" json:"onSale,omitempty"`
	AddTime         int64                      `protobuf:"varint,20,opt,name=addTime,proto3" json:"addTime,omitempty"`
	Category        *CategoryBriefInfoResponse `protobuf:"bytes,21,opt,name=category,proto3" json:"category,omitempty"`
	Brand           *BrandInfoResponse         `protobuf:"bytes,22,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GoodsInfoResponse) Reset() {
	*x = GoodsInfoResponse{}
	mi := &file_goods_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoResponse) ProtoMessage() {}

func (x *GoodsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoResponse.ProtoReflect.Descriptor instead.
func (*GoodsInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfoResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoResponse) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *GoodsInfoResponse) GetClickNum() int32 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetSoldNum() int32 {
	if x != nil {
		return x.SoldNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetFavNum() int32 {
	if x != nil {
		return x.FavNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetMarketPrice() float32 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *GoodsInfoResponse) GetShopPrice() float32 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *GoodsInfoResponse) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *GoodsInfoResponse) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *GoodsInfoResponse) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *GoodsInfoResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GoodsInfoResponse) GetDescImages() []string {
	if x != nil {
		return x.DescImages
	}
	return nil
}

func (x *GoodsInfoResponse) GetGoodsFrontImage() string {
	if x != nil {
		return x.GoodsFrontImage
	}
	return ""
}

func (x *GoodsInfoResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodsInfoResponse) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodsInfoResponse) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *GoodsInfoResponse) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *GoodsInfoResponse) GetCategory() *CategoryBriefInfoResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *GoodsInfoResponse) GetBrand() *BrandInfoResponse {
	if x != nil {
		return x.Brand
	}
	return nil
}

type DeleteGoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoodsInfo) Reset() {
	*x = DeleteGoodsInfo{}
	mi := &file_goods_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoodsInfo) ProtoMessage() {}

func (x *DeleteGoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoodsInfo.ProtoReflect.Descriptor instead.
func (*DeleteGoodsInfo) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGoodsInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodInfoRequest) Reset() {
	*x = GoodInfoRequest{}
	mi := &file_goods_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodInfoRequest) ProtoMessage() {}

func (x *GoodInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodInfoRequest.ProtoReflect.Descriptor instead.
func (*GoodInfoRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{7}
}

func (x *GoodInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CategoryBrandInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentCategory int32                  `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"`
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	IsTab          bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryBrandInfoRequest) Reset() {
	*x = CategoryBrandInfoRequest{}
	mi := &file_goods_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandInfoRequest) ProtoMessage() {}

func (x *CategoryBrandInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandInfoRequest.ProtoReflect.Descriptor instead.
func (*CategoryBrandInfoRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryBrandInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBrandInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryBrandInfoRequest) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryBrandInfoRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryBrandInfoRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

type CategoryBrandFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandFilterRequest) Reset() {
	*x = CategoryBrandFilterRequest{}
	mi := &file_goods_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandFilterRequest) ProtoMessage() {}

func (x *CategoryBrandFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandFilterRequest.ProtoReflect.Descriptor instead.
func (*CategoryBrandFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryBrandFilterRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CategoryBrandFilterRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CategoryBrandListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Total         int32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*CategoryBrandResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandListResponse) Reset() {
	*x = CategoryBrandListResponse{}
	mi := &file_goods_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandListResponse) ProtoMessage() {}

func (x *CategoryBrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandListResponse.ProtoReflect.Descriptor instead.
func (*CategoryBrandListResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryBrandListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryBrandListResponse) GetData() []*CategoryBrandResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type CategoryBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	BrandId       int32                  `protobuf:"varint,3,opt,name=brandId,proto3" json:"brandId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandRequest) Reset() {
	*x = CategoryBrandRequest{}
	mi := &file_goods_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandRequest) ProtoMessage() {}

func (x *CategoryBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandRequest.ProtoReflect.Descriptor instead.
func (*CategoryBrandRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{11}
}

func (x *CategoryBrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBrandRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryBrandRequest) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

type CategoryBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         *BrandInfoResponse     `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Category      *CategoryInfoResponse  `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandResponse) Reset() {
	*x = CategoryBrandResponse{}
	mi := &file_goods_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandResponse) ProtoMessage() {}

func (x *CategoryBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandResponse.ProtoReflect.Descriptor instead.
func (*CategoryBrandResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{12}
}

func (x *CategoryBrandResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBrandResponse) GetBrand() *BrandInfoResponse {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *CategoryBrandResponse) GetCategory() *CategoryInfoResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

type CategoryFilterFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsTab         bool                   `protobuf:"varint,2,opt,name=isTab,proto3" json:"isTab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFilterFilterRequest) Reset() {
	*x = CategoryFilterFilterRequest{}
	mi := &file_goods_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFilterFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFilterFilterRequest) ProtoMessage() {}

func (x *CategoryFilterFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFilterFilterRequest.ProtoReflect.Descriptor instead.
func (*CategoryFilterFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{13}
}

func (x *CategoryFilterFilterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryFilterFilterRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

type CategoryListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*CategoryInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	JsonData      string                  `protobuf:"bytes,3,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_goods_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{14}
}

func (x *CategoryListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryListResponse) GetData() []*CategoryInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CategoryListResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type CategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_goods_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{15}
}

func (x *CategoryListRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryListRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SubCategoryListResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Total           int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Info            *CategoryInfoResponse   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	SubCategoryList []*CategoryInfoResponse `protobuf:"bytes,3,rep,name=subCategoryList,proto3" json:"subCategoryList,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubCategoryListResponse) Reset() {
	*x = SubCategoryListResponse{}
	mi := &file_goods_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryListResponse) ProtoMessage() {}

func (x *SubCategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryListResponse.ProtoReflect.Descriptor instead.
func (*SubCategoryListResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{16}
}

func (x *SubCategoryListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubCategoryListResponse) GetInfo() *CategoryInfoResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SubCategoryListResponse) GetSubCategoryList() []*CategoryInfoResponse {
	if x != nil {
		return x.SubCategoryList
	}
	return nil
}

type CategoryInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentCategory int32                  `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"`
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	IsTab          bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryInfoResponse) Reset() {
	*x = CategoryInfoResponse{}
	mi := &file_goods_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoResponse) ProtoMessage() {}

func (x *CategoryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoResponse.ProtoReflect.Descriptor instead.
func (*CategoryInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{17}
}

func (x *CategoryInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoResponse) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoResponse) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

type DeleteCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryInfo) Reset() {
	*x = DeleteCategoryInfo{}
	mi := &file_goods_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryInfo) ProtoMessage() {}

func (x *DeleteCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryInfo.ProtoReflect.Descriptor instead.
func (*DeleteCategoryInfo) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteCategoryInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QueryCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCategoryRequest) Reset() {
	*x = QueryCategoryRequest{}
	mi := &file_goods_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryRequest) ProtoMessage() {}

func (x *QueryCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryRequest.ProtoReflect.Descriptor instead.
func (*QueryCategoryRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{19}
}

func (x *QueryCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BatchCategoryInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int32                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	GoodsNums     int32                  `protobuf:"varint,2,opt,name=goodsNums,proto3" json:"goodsNums,omitempty"`
	BrandNums     int32                  `protobuf:"varint,3,opt,name=brandNums,proto3" json:"brandNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCategoryInfoRequest) Reset() {
	*x = BatchCategoryInfoRequest{}
	mi := &file_goods_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCategoryInfoRequest) ProtoMessage() {}

func (x *BatchCategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchCategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{20}
}

func (x *BatchCategoryInfoRequest) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BatchCategoryInfoRequest) GetGoodsNums() int32 {
	if x != nil {
		return x.GoodsNums
	}
	return 0
}

func (x *BatchCategoryInfoRequest) GetBrandNums() int32 {
	if x != nil {
		return x.BrandNums
	}
	return 0
}

type CategoryInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentCategory int32                  `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"`
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	IsTab          bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryInfoRequest) Reset() {
	*x = CategoryInfoRequest{}
	mi := &file_goods_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoRequest) ProtoMessage() {}

func (x *CategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*CategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{21}
}

func (x *CategoryInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoRequest) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

type BrandFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandFilterRequest) Reset() {
	*x = BrandFilterRequest{}
	mi := &file_goods_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandFilterRequest) ProtoMessage() {}

func (x *BrandFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandFilterRequest.ProtoReflect.Descriptor instead.
func (*BrandFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{22}
}

func (x *BrandFilterRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BrandFilterRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BrandListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*BrandInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandListResponse) Reset() {
	*x = BrandListResponse{}
	mi := &file_goods_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandListResponse) ProtoMessage() {}

func (x *BrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandListResponse.ProtoReflect.Descriptor instead.
func (*BrandListResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{23}
}

func (x *BrandListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BrandListResponse) GetData() []*BrandInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type BrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandRequest) Reset() {
	*x = BrandRequest{}
	mi := &file_goods_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandRequest) ProtoMessage() {}

func (x *BrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandRequest.ProtoReflect.Descriptor instead.
func (*BrandRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{24}
}

func (x *BrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

type BrandInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandInfoResponse) Reset() {
	*x = BrandInfoResponse{}
	mi := &file_goods_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandInfoResponse) ProtoMessage() {}

func (x *BrandInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandInfoResponse.ProtoReflect.Descriptor instead.
func (*BrandInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{25}
}

func (x *BrandInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandInfoResponse) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

type BannerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*BannerResponse      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerListResponse) Reset() {
	*x = BannerListResponse{}
	mi := &file_goods_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerListResponse) ProtoMessage() {}

func (x *BannerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerListResponse.ProtoReflect.Descriptor instead.
func (*BannerListResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{26}
}

func (x *BannerListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BannerListResponse) GetData() []*BannerResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type BannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerRequest) Reset() {
	*x = BannerRequest{}
	mi := &file_goods_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerRequest) ProtoMessage() {}

func (x *BannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerRequest.ProtoReflect.Descriptor instead.
func (*BannerRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{27}
}

func (x *BannerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BannerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type BannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponse) Reset() {
	*x = BannerResponse{}
	mi := &file_goods_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponse) ProtoMessage() {}

func (x *BannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponse.ProtoReflect.Descriptor instead.
func (*BannerResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{28}
}

func (x *BannerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BannerResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_goods_proto protoreflect.FileDescriptor

const file_goods_proto_rawDesc = "" +
	"\n" +
	"\vgoods.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x02\n" +
	"\x12GoodsFilterRequest\x12\x1a\n" +
	"\bpriceMin\x18\x01 \x01(\x05R\bpriceMin\x12\x1a\n" +
	"\bpriceMax\x18\x02 \x01(\x05R\bpriceMax\x12\x14\n" +
	"\x05isHot\x18\x03 \x01(\bR\x05isHot\x12\x14\n" +
	"\x05isNew\x18\x04 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\x12 \n" +
	"\vtopCategory\x18\x06 \x01(\x05R\vtopCategory\x12\x12\n" +
	"\x04page\x18\a \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\b \x01(\rR\x04size\x12\x1a\n" +
	"\bkeyWords\x18\t \x01(\tR\bkeyWords\x12\x14\n" +
	"\x05brand\x18\n" +
	" \x01(\x05R\x05brand\"Q\n" +
	"\x11GoodsListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.GoodsInfoResponseR\x04data\"\"\n" +
	"\x10BatchGoodsIdInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\"\xe1\x03\n" +
	"\x0fCreateGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\agoodsSn\x18\x03 \x01(\tR\agoodsSn\x12\x16\n" +
	"\x06stocks\x18\a \x01(\x05R\x06stocks\x12 \n" +
	"\vmarketPrice\x18\b \x01(\x02R\vmarketPrice\x12\x1c\n" +
	"\tshopPrice\x18\t \x01(\x02R\tshopPrice\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\n" +
	" \x01(\tR\n" +
	"goodsBrief\x12\x1c\n" +
	"\tgoodsDesc\x18\v \x01(\tR\tgoodsDesc\x12\x1a\n" +
	"\bshipFree\x18\f \x01(\bR\bshipFree\x12\x16\n" +
	"\x06images\x18\r \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"descImages\x18\x0e \x03(\tR\n" +
	"descImages\x12(\n" +
	"\x0fgoodsFrontImage\x18\x0f \x01(\tR\x0fgoodsFrontImage\x12\x14\n" +
	"\x05isNew\x18\x10 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x11 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x12 \x01(\bR\x06onSale\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x13 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x14 \x01(\x05R\abrandId\"?\n" +
	"\x19CategoryBriefInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xfb\x04\n" +
	"\x11GoodsInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\agoodsSn\x18\x04 \x01(\tR\agoodsSn\x12\x1a\n" +
	"\bclickNum\x18\x05 \x01(\x05R\bclickNum\x12\x18\n" +
	"\asoldNum\x18\x06 \x01(\x05R\asoldNum\x12\x16\n" +
	"\x06favNum\x18\a \x01(\x05R\x06favNum\x12 \n" +
	"\vmarketPrice\x18\t \x01(\x02R\vmarketPrice\x12\x1c\n" +
	"\tshopPrice\x18\n" +
	" \x01(\x02R\tshopPrice\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\v \x01(\tR\n" +
	"goodsBrief\x12\x1c\n" +
	"\tgoodsDesc\x18\f \x01(\tR\tgoodsDesc\x12\x1a\n" +
	"\bshipFree\x18\r \x01(\bR\bshipFree\x12\x16\n" +
	"\x06images\x18\x0e \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"descImages\x18\x0f \x03(\tR\n" +
	"descImages\x12(\n" +
	"\x0fgoodsFrontImage\x18\x10 \x01(\tR\x0fgoodsFrontImage\x12\x14\n" +
	"\x05isNew\x18\x11 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x12 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x13 \x01(\bR\x06onSale\x12\x18\n" +
	"\aaddTime\x18\x14 \x01(\x03R\aaddTime\x126\n" +
	"\bcategory\x18\x15 \x01(\v2\x1a.CategoryBriefInfoResponseR\bcategory\x12(\n" +
	"\x05brand\x18\x16 \x01(\v2\x12.BrandInfoResponseR\x05brand\"!\n" +
	"\x0fDeleteGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"!\n" +
	"\x0fGoodInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x92\x01\n" +
	"\x18CategoryBrandInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\"D\n" +
	"\x1aCategoryBrandFilterRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"]\n" +
	"\x19CategoryBrandListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.CategoryBrandResponseR\x04data\"`\n" +
	"\x14CategoryBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x03 \x01(\x05R\abrandId\"\x84\x01\n" +
	"\x15CategoryBrandResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12(\n" +
	"\x05brand\x18\x02 \x01(\v2\x12.BrandInfoResponseR\x05brand\x121\n" +
	"\bcategory\x18\x03 \x01(\v2\x15.CategoryInfoResponseR\bcategory\"C\n" +
	"\x1bCategoryFilterFilterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05isTab\x18\x02 \x01(\bR\x05isTab\"s\n" +
	"\x14CategoryListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12)\n" +
	"\x04data\x18\x02 \x03(\v2\x15.CategoryInfoResponseR\x04data\x12\x1a\n" +
	"\bjsonData\x18\x03 \x01(\tR\bjsonData\";\n" +
	"\x13CategoryListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\x9b\x01\n" +
	"\x17SubCategoryListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12)\n" +
	"\x04info\x18\x02 \x01(\v2\x15.CategoryInfoResponseR\x04info\x12?\n" +
	"\x0fsubCategoryList\x18\x03 \x03(\v2\x15.CategoryInfoResponseR\x0fsubCategoryList\"\x8e\x01\n" +
	"\x14CategoryInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\"$\n" +
	"\x12DeleteCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\":\n" +
	"\x14QueryCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"f\n" +
	"\x18BatchCategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\x12\x1c\n" +
	"\tgoodsNums\x18\x02 \x01(\x05R\tgoodsNums\x12\x1c\n" +
	"\tbrandNums\x18\x03 \x01(\x05R\tbrandNums\"\x8d\x01\n" +
	"\x13CategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\"<\n" +
	"\x12BrandFilterRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"Q\n" +
	"\x11BrandListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.BrandInfoResponseR\x04data\"F\n" +
	"\fBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\"K\n" +
	"\x11BrandInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\"O\n" +
	"\x12BannerListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12#\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.BannerResponseR\x04data\"]\n" +
	"\rBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"^\n" +
	"\x0eBannerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url2\xb0\v\n" +
	"\x05Goods\x124\n" +
	"\tGoodsList\x12\x13.GoodsFilterRequest\x1a\x12.GoodsListResponse\x126\n" +
	"\rBatchGetGoods\x12\x11.BatchGoodsIdInfo\x1a\x12.GoodsListResponse\x123\n" +
	"\vCreateGoods\x12\x10.CreateGoodsInfo\x1a\x12.GoodsInfoResponse\x127\n" +
	"\vDeleteGoods\x12\x10.DeleteGoodsInfo\x1a\x16.google.protobuf.Empty\x127\n" +
	"\vUpdateGoods\x12\x10.CreateGoodsInfo\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x0eGetGoodsDetail\x12\x10.GoodInfoRequest\x1a\x12.GoodsInfoResponse\x12C\n" +
	"\x12GetAllCategoryList\x12\x16.google.protobuf.Empty\x1a\x15.CategoryListResponse\x12@\n" +
	"\x0eGetSubCategory\x12\x14.CategoryListRequest\x1a\x18.SubCategoryListResponse\x12=\n" +
	"\x0eCreateCategory\x12\x14.CategoryInfoRequest\x1a\x15.CategoryInfoResponse\x12=\n" +
	"\x0eDeleteCategory\x12\x13.DeleteCategoryInfo\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x0eUpdateCategory\x12\x14.CategoryInfoRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x11CategoryBrandList\x12\x1b.CategoryBrandFilterRequest\x1a\x1a.CategoryBrandListResponse\x12E\n" +
	"\x14GetCategoryBrandList\x12\x19.CategoryBrandInfoRequest\x1a\x12.BrandListResponse\x12D\n" +
	"\x13CreateCategoryBrand\x12\x15.CategoryBrandRequest\x1a\x16.CategoryBrandResponse\x12D\n" +
	"\x13DeleteCategoryBrand\x12\x15.CategoryBrandRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x13UpdateCategoryBrand\x12\x15.CategoryBrandRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\tBrandList\x12\x13.BrandFilterRequest\x1a\x12.BrandListResponse\x120\n" +
	"\vCreateBrand\x12\r.BrandRequest\x1a\x12.BrandInfoResponse\x124\n" +
	"\vDeleteBrand\x12\r.BrandRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\vUpdateBrand\x12\r.BrandRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\n" +
	"BannerList\x12\x16.google.protobuf.Empty\x1a\x13.BannerListResponse\x12/\n" +
	"\fCreateBanner\x12\x0e.BannerRequest\x1a\x0f.BannerResponse\x126\n" +
	"\fDeleteBanner\x12\x0e.BannerRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\fUpdateBanner\x12\x0e.BannerRequest\x1a\x16.google.protobuf.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_goods_proto_rawDescOnce sync.Once
	file_goods_proto_rawDescData []byte
)

func file_goods_proto_rawDescGZIP() []byte {
	file_goods_proto_rawDescOnce.Do(func() {
		file_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)))
	})
	return file_goods_proto_rawDescData
}

var file_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_goods_proto_goTypes = []any{
	(*GoodsFilterRequest)(nil),          // 0: GoodsFilterRequest
	(*GoodsListResponse)(nil),           // 1: GoodsListResponse
	(*BatchGoodsIdInfo)(nil),            // 2: BatchGoodsIdInfo
	(*CreateGoodsInfo)(nil),             // 3: CreateGoodsInfo
	(*CategoryBriefInfoResponse)(nil),   // 4: CategoryBriefInfoResponse
	(*GoodsInfoResponse)(nil),           // 5: GoodsInfoResponse
	(*DeleteGoodsInfo)(nil),             // 6: DeleteGoodsInfo
	(*GoodInfoRequest)(nil),             // 7: GoodInfoRequest
	(*CategoryBrandInfoRequest)(nil),    // 8: CategoryBrandInfoRequest
	(*CategoryBrandFilterRequest)(nil),  // 9: CategoryBrandFilterRequest
	(*CategoryBrandListResponse)(nil),   // 10: CategoryBrandListResponse
	(*CategoryBrandRequest)(nil),        // 11: CategoryBrandRequest
	(*CategoryBrandResponse)(nil),       // 12: CategoryBrandResponse
	(*CategoryFilterFilterRequest)(nil), // 13: CategoryFilterFilterRequest
	(*CategoryListResponse)(nil),        // 14: CategoryListResponse
	(*CategoryListRequest)(nil),         // 15: CategoryListRequest
	(*SubCategoryListResponse)(nil),     // 16: SubCategoryListResponse
	(*CategoryInfoResponse)(nil),        // 17: CategoryInfoResponse
	(*DeleteCategoryInfo)(nil),          // 18: DeleteCategoryInfo
	(*QueryCategoryRequest)(nil),        // 19: QueryCategoryRequest
	(*BatchCategoryInfoRequest)(nil),    // 20: BatchCategoryInfoRequest
	(*CategoryInfoRequest)(nil),         // 21: CategoryInfoRequest
	(*BrandFilterRequest)(nil),          // 22: BrandFilterRequest
	(*BrandListResponse)(nil),           // 23: BrandListResponse
	(*BrandRequest)(nil),                // 24: BrandRequest
	(*BrandInfoResponse)(nil),           // 25: BrandInfoResponse
	(*BannerListResponse)(nil),          // 26: BannerListResponse
	(*BannerRequest)(nil),               // 27: BannerRequest
	(*BannerResponse)(nil),              // 28: BannerResponse
	(*emptypb.Empty)(nil),               // 29: google.protobuf.Empty
}
var file_goods_proto_depIdxs = []int32{
	5,  // 0: GoodsListResponse.data:type_name -> GoodsInfoResponse
	4,  // 1: GoodsInfoResponse.category:type_name -> CategoryBriefInfoResponse
	25, // 2: GoodsInfoResponse.brand:type_name -> BrandInfoResponse
	12, // 3: CategoryBrandListResponse.data:type_name -> CategoryBrandResponse
	25, // 4: CategoryBrandResponse.brand:type_name -> BrandInfoResponse
	17, // 5: CategoryBrandResponse.category:type_name -> CategoryInfoResponse
	17, // 6: CategoryListResponse.data:type_name -> CategoryInfoResponse
	17, // 7: SubCategoryListResponse.info:type_name -> CategoryInfoResponse
	17, // 8: SubCategoryListResponse.subCategoryList:type_name -> CategoryInfoResponse
	25, // 9: BrandListResponse.data:type_name -> BrandInfoResponse
	28, // 10: BannerListResponse.data:type_name -> BannerResponse
	0,  // 11: Goods.GoodsList:input_type -> GoodsFilterRequest
	2,  // 12: Goods.BatchGetGoods:input_type -> BatchGoodsIdInfo
	3,  // 13: Goods.CreateGoods:input_type -> CreateGoodsInfo
	6,  // 14: Goods.DeleteGoods:input_type -> DeleteGoodsInfo
	3,  // 15: Goods.UpdateGoods:input_type -> CreateGoodsInfo
	7,  // 16: Goods.GetGoodsDetail:input_type -> GoodInfoRequest
	29, // 17: Goods.GetAllCategoryList:input_type -> google.protobuf.Empty
	15, // 18: Goods.GetSubCategory:input_type -> CategoryListRequest
	21, // 19: Goods.CreateCategory:input_type -> CategoryInfoRequest
	18, // 20: Goods.DeleteCategory:input_type -> DeleteCategoryInfo
	21, // 21: Goods.UpdateCategory:input_type -> CategoryInfoRequest
	9,  // 22: Goods.CategoryBrandList:input_type -> CategoryBrandFilterRequest
	8,  // 23: Goods.GetCategoryBrandList:input_type -> CategoryBrandInfoRequest
	11, // 24: Goods.CreateCategoryBrand:input_type -> CategoryBrandRequest
	11, // 25: Goods.DeleteCategoryBrand:input_type -> CategoryBrandRequest
	11, // 26: Goods.UpdateCategoryBrand:input_type -> CategoryBrandRequest
	22, // 27: Goods.BrandList:input_type -> BrandFilterRequest
	24, // 28: Goods.CreateBrand:input_type -> BrandRequest
	24, // 29: Goods.DeleteBrand:input_type -> BrandRequest
	24, // 30: Goods.UpdateBrand:input_type -> BrandRequest
	29, // 31: Goods.BannerList:input_type -> google.protobuf.Empty
	27, // 32: Goods.CreateBanner:input_type -> BannerRequest
	27, // 33: Goods.DeleteBanner:input_type -> BannerRequest
	27, // 34: Goods.UpdateBanner:input_type -> BannerRequest
	1,  // 35: Goods.GoodsList:output_type -> GoodsListResponse
	1,  // 36: Goods.BatchGetGoods:output_type -> GoodsListResponse
	5,  // 37: Goods.CreateGoods:output_type -> GoodsInfoResponse
	29, // 38: Goods.DeleteGoods:output_type -> google.protobuf.Empty
	29, // 39: Goods.UpdateGoods:output_type -> google.protobuf.Empty
	5,  // 40: Goods.GetGoodsDetail:output_type -> GoodsInfoResponse
	14, // 41: Goods.GetAllCategoryList:output_type -> CategoryListResponse
	16, // 42: Goods.GetSubCategory:output_type -> SubCategoryListResponse
	17, // 43: Goods.CreateCategory:output_type -> CategoryInfoResponse
	29, // 44: Goods.DeleteCategory:output_type -> google.protobuf.Empty
	29, // 45: Goods.UpdateCategory:output_type -> google.protobuf.Empty
	10, // 46: Goods.CategoryBrandList:output_type -> CategoryBrandListResponse
	23, // 47: Goods.GetCategoryBrandList:output_type -> BrandListResponse
	12, // 48: Goods.CreateCategoryBrand:output_type -> CategoryBrandResponse
	29, // 49: Goods.DeleteCategoryBrand:output_type -> google.protobuf.Empty
	29, // 50: Goods.UpdateCategoryBrand:output_type -> google.protobuf.Empty
	23, // 51: Goods.BrandList:output_type -> BrandListResponse
	25, // 52: Goods.CreateBrand:output_type -> BrandInfoResponse
	29, // 53: Goods.DeleteBrand:output_type -> google.protobuf.Empty
	29, // 54: Goods.UpdateBrand:output_type -> google.protobuf.Empty
	26, // 55: Goods.BannerList:output_type -> BannerListResponse
	28, // 56: Goods.CreateBanner:output_type -> BannerResponse
	29, // 57: Goods.DeleteBanner:output_type -> google.protobuf.Empty
	29, // 58: Goods.UpdateBanner:output_type -> google.protobuf.Empty
	35, // [35:59] is the sub-list for method output_type
	11, // [11:35] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_goods_proto_init() }
func file_goods_proto_init() {
	if File_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_proto_goTypes,
		DependencyIndexes: file_goods_proto_depIdxs,
		MessageInfos:      file_goods_proto_msgTypes,
	}.Build()
	File_goods_proto = out.File
	file_goods_proto_goTypes = nil
	file_goods_proto_depIdxs = nil
}
