# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_srv/proto/role.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_srv/proto/role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from common.proto import common_pb2 as common_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19user_srv/proto/role.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19\x63ommon/proto/common.proto\">\n\x0e\x43reateRoleInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06remark\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\"L\n\x10RoleInfoResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\"J\n\x0eUpdateRoleInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\"g\n\x12RoleFilterPageInfo\x12#\n\tpage_info\x18\x01 \x01(\x0b\x32\x10.common.PageInfo\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\"B\n\x10RoleListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.RoleInfoResponse2\xa6\x01\n\x04Role\x12\x30\n\nCreateRole\x12\x0f.CreateRoleInfo\x1a\x11.RoleInfoResponse\x12\x35\n\nUpdateRole\x12\x0f.UpdateRoleInfo\x1a\x16.google.protobuf.Empty\x12\x35\n\x0bGetRoleList\x12\x13.RoleFilterPageInfo\x1a\x11.RoleListResponseB\tZ\x07.;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_srv.proto.role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007.;proto'
  _globals['_CREATEROLEINFO']._serialized_start=85
  _globals['_CREATEROLEINFO']._serialized_end=147
  _globals['_ROLEINFORESPONSE']._serialized_start=149
  _globals['_ROLEINFORESPONSE']._serialized_end=225
  _globals['_UPDATEROLEINFO']._serialized_start=227
  _globals['_UPDATEROLEINFO']._serialized_end=301
  _globals['_ROLEFILTERPAGEINFO']._serialized_start=303
  _globals['_ROLEFILTERPAGEINFO']._serialized_end=406
  _globals['_ROLELISTRESPONSE']._serialized_start=408
  _globals['_ROLELISTRESPONSE']._serialized_end=474
  _globals['_ROLE']._serialized_start=477
  _globals['_ROLE']._serialized_end=643
# @@protoc_insertion_point(module_scope)
